# Generated by Django 5.1.2 on 2024-10-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athletes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('Sex', models.CharField(max_length=2)),
                ('Event', models.CharField(max_length=3)),
                ('Equipment', models.CharField(max_length=24)),
                ('Division', models.CharField(max_length=32)),
                ('WeightClassKg', models.CharField(max_length=4)),
                ('TotalKg', models.FloatField()),
                ('Federation', models.CharField(max_length=16)),
                ('Date', models.CharField(max_length=24)),
                ('MeetName', models.CharField(max_length=128)),
            ],
        ),
    ]
