# Generated by Django 5.1.2 on 2024-11-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('Sex', models.CharField(max_length=2)),
                ('Event', models.CharField(max_length=4)),
                ('Equipment', models.CharField(max_length=32)),
                ('Age', models.IntegerField()),
                ('Division', models.CharField(max_length=32)),
                ('BodyweightKg', models.FloatField()),
                ('WeightClassKg', models.CharField(max_length=4)),
                ('BestSquatKg', models.FloatField()),
                ('BestBenchKg', models.FloatField()),
                ('BestDeadliftKg', models.FloatField()),
                ('TotalKg', models.FloatField()),
                ('Place', models.IntegerField()),
                ('IPFGLPoints', models.FloatField()),
                ('Country', models.CharField(max_length=64)),
                ('Federation', models.CharField(max_length=32)),
                ('Date', models.CharField(max_length=16)),
                ('MeetName', models.CharField(max_length=128)),
            ],
        ),
    ]
