# Generated by Django 5.1.5 on 2025-01-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Competition',
            new_name='Performance',
        ),
    ]
